# Generated by Django 2.2.5 on 2019-10-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gpl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=30)),
                ('owner', models.CharField(max_length=30)),
                ('phoneno', models.IntegerField()),
                ('captain', models.CharField(max_length=30)),
                ('icon', models.CharField(max_length=30)),
                ('golden', models.CharField(max_length=30)),
            ],
        ),
    ]
