# Generated by Django 2.2.5 on 2019-09-20 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Eid', models.IntegerField()),
                ('Ename', models.CharField(max_length=40)),
                ('Esal', models.FloatField()),
                ('Eaddr', models.CharField(max_length=40)),
            ],
        ),
    ]
