# Generated by Django 2.2.5 on 2019-11-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titile', models.CharField(max_length=256)),
                ('auther', models.CharField(max_length=64)),
                ('pages', models.PositiveIntegerField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
