# Generated by Django 2.2.5 on 2019-09-25 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sid', models.IntegerField()),
                ('Sname', models.CharField(max_length=40)),
                ('Ssal', models.IntegerField()),
                ('Saddr', models.CharField(max_length=40)),
            ],
        ),
    ]
