# Generated by Django 2.2.5 on 2019-11-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('category', models.CharField(max_length=64)),
                ('grade', models.CharField(max_length=64)),
                ('price', models.FloatField()),
                ('phoneno', models.IntegerField()),
            ],
        ),
    ]
