# Generated by Django 2.2.5 on 2019-12-08 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emplyoee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=120)),
                ('eid', models.IntegerField()),
                ('esal', models.FloatField()),
                ('eaddrs', models.CharField(max_length=120)),
            ],
        ),
    ]
