# Generated by Django 2.2.5 on 2019-11-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('test', models.CharField(max_length=64)),
                ('color', models.CharField(max_length=64)),
                ('price', models.FloatField()),
            ],
        ),
    ]
