# Generated by Django 2.2.5 on 2019-10-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviename', models.CharField(max_length=30)),
                ('rdate', models.DateField()),
                ('hero', models.CharField(max_length=30)),
                ('heroin', models.CharField(max_length=30)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
